version: "3"
services: 
    app:
        build:
            context: .
            dockerfile: ./app/Dockerfile
        networks: 
            - redis
        depends_on: 
            - redis
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes: 
            - "./data/redis:/data"
        networks: 
            - redis
    redisinsight:
        image: redislabs/redisinsight:latest
        ports: 
            - "8001:8001"
        volumes: 
            - ./redisinsight:/db
        networks: 
            - redis
networks: 
    redis:
        driver: bridge
